### PR TITLE
feat: customize sidebar style

### PR DESCRIPTION
**Pull request by MekalaNagarajan-Centrica**

### CODE REVIEW

**Review by RobTobias123 — APPROVED** [review]
Looks good to me.

**Comment by andij** [comment]
Are we able to retain the badges on the links like this from the frontmatter: 

- [Component](#!) `new`
- [Old component](#!) `deprecated`

In the frontmatter:

```markdown
---
title: Old component
sidebar:
  badge: deprecated
---
```

**Comment by andij** [comment]
I notice the order of the components is no longer alphabetical, can we set the order?

**Comment by andij** [comment]
The `@internal` components are being displayed e.g. `ns-tab`. I assume this is something we can introduce into the JSDocs to hide them.

**Review by andij — APPROVED** [review]

**Pull request merged**
