### PR TITLE
Add spcaing to ns-content

### PR DESCRIPTION
**Pull request by dbenmore**

### CODE REVIEW

**Review by RobTobias123 — APPROVED** [review]
Looks good to me.

**Review by PtitBen — COMMENTED** [review]
I wonder if a spacing section with a quick definition of compact, cosy, normal and loose would be a nice addition?

**Comment by dbenmore** [comment]
@PtitBen I've added a table for the spacing values

**Review by PtitBen — APPROVED** [review]
Nice and simple :) 
Thanks for that !

All good to go for me now

**Pull request merged**
