### PR TITLE
Epic/page types

### PR DESCRIPTION
**Pull request by andij**
Page types:
- [x] Confirmation
- [x] Home
- [x] Start

### CODE REVIEW

**Comment by dbenmore** [comment]
A couple of things about the Page composition tables

* Can you link to the .md files for the components rather than live urls? this will fail the build if the filename or file location changes
* I'm not sure about the emmet abbreviations. What's the benefit of those vs a html example? If we're to keep them then we should explain what they are - they seem out of place and lack context. Perhaps create a component to help maintain them?

**Comment by andij** [comment]
I've changed the URLs in the table to be relative and link to the .md file

And I agree that the Emmet snippets should be removed. At least until we agree that they're valuable and have a nice way to implement them and provide the correct context.

**Review by PtitBen — APPROVED** [review]

**Comment by PtitBen** [comment]
I couldn't check the deploy preview, but looking at the individual rich diffs, all looks good to me. 
I liked the Emmet code, but it may need an introduction somewhere before we start adding it :) 

But I really like it!

**Comment by andij** [comment]
@PtitBen, Thanks for the review. Apologies that the Deploy preview failed. It's because I'm linking to the `ns-timeline` docs page that doesn't yet exist in this PR.

**Review by dbenmore — APPROVED** [review]

**Pull request merged**
